{- This file is generated by the 'scripts/gen_package.py' script -}
{ Config =
    ./schemas/Config.dhall sha256:4863abb676d45fdd59003991f78f80d59815b3f4a12a25906a5b74573084c166
, DiskImage =
    ./schemas/DiskImage.dhall sha256:400b080da0339e476da88df7e395abde258bfd3c63d1a8bfa125643aabc393ed
, Label =
    ./schemas/Label.dhall sha256:57c0b99faadd31679c690a00b2eac11f17245e291e8f0002fe17bd07f85cbbb7
, Openshiftpods =
    ./schemas/Openshiftpods.dhall sha256:fdba3b1b478119cc2b872edeb6b90deffd6137427f5f118c55c486b93ca17ace
, OpenshiftpodsLabels =
    ./schemas/OpenshiftpodsLabels.dhall sha256:d3eebc9b500d7fa2674db854ed5c9ba8c365311023bddffa013853eb8b640c83
, OpenshiftpodsPools =
    ./schemas/OpenshiftpodsPools.dhall sha256:8d6f247dc98a18a61439c1107c3413c5a8aa5f5d9a5c283c5a4ccd5ac9a77536
, Openstack =
    ./schemas/Openstack.dhall sha256:85cdfdc653483fc188858e7cded4d151bd67049f60fe2e9897946b52efc445ab
, OpenstackCloudImage =
    ./schemas/OpenstackCloudImage.dhall sha256:100b970c9a5d54f76292918e49472ad40924c52f8ff89081c2850adbfc0ff193
, OpenstackDiskImage =
    ./schemas/OpenstackDiskImage.dhall sha256:1931b7aa281d70d80baf81499221cd36909b02f0839a24f1b314220fd962aca9
, OpenstackLabel =
    ./schemas/OpenstackLabel.dhall sha256:f954dc590c230844d2603c81be90b3f7319e08b44ae5d940dd73a07db454a6f7
, OpenstackPool =
    ./schemas/OpenstackPool.dhall sha256:51cdc659873bd148f4fcb0eead5ea1f6ffb845b93ae323058e7e3df8d2f8c071
, Providers =
    ./schemas/Providers.dhall sha256:b6801e4e916583f37cfa953d09c3ef38dc6f58023491c52b32c90dd6ebaaaf74
, Static =
    ./schemas/Static.dhall sha256:0ca2644693c08f8a867e24610f0a31c9ef1ed91d855e41a14e20e875511110e4
, StaticPool =
    ./schemas/StaticPool.dhall sha256:3d08c25e8a5c1814f95d49d99742666e111c27f41a557d99d3ad5b0f02523d24
, StaticPoolNode =
    ./schemas/StaticPoolNode.dhall sha256:bb96f4740de46bc5d60cd226402acd042340544a837d28a3c9a616308fd34e63
, WebApp =
    ./schemas/WebApp.dhall sha256:0e3cde952af63619172b62506a55c64b2f4ce4dce4c900b9603d79848c151f4a
, ZookeeperServer =
    ./schemas/ZookeeperServer.dhall sha256:8fb4a851f4a2d610e81ba77566531aef518f4452317c436bdec61a0e32d95135
}
