{- This file is generated by the 'scripts/gen_package.py' script -}
{ Aws =
    ./schemas/Aws.dhall sha256:11a06a95148ab7ecbbce1a602b32e3e9b98f24f9f78f1eb21116b999d8396dfc
, AwsCloudImage =
    ./schemas/AwsCloudImage.dhall sha256:08aa481d1393681d89cb32dddaf6c4cac565eedd64e8e3b4995ea886c8f92e85
, AwsCloudImageImageFilter =
    ./schemas/AwsCloudImageImageFilter.dhall sha256:5cf9a56f6663e8da50d6e2ba95d5b8e2ec5e1dd9ab5d57f9195ba0e03d44ba7a
, AwsPool =
    ./schemas/AwsPool.dhall sha256:8b8f86da4c591e1b35f2e7bc9606baef19c45ee52c2efe915b0d3cb12891ff83
, AwsPoolLabel =
    ./schemas/AwsPoolLabel.dhall sha256:7d51300d50064549cbf409e6f360a149ab1f3919a684f1d0566063f86b50cdf6
, Config =
    ./schemas/Config.dhall sha256:57fe0e0431afc7bddce20b5cd88c9ea420149292e8b1becd0baa83324c375fea
, DiskImage =
    ./schemas/DiskImage.dhall sha256:400b080da0339e476da88df7e395abde258bfd3c63d1a8bfa125643aabc393ed
, Gce =
    ./schemas/Gce.dhall sha256:352cf7f765d940ca926dced5834661394a25fefbeed56093c10b58f5d8668c20
, GceCloudImage =
    ./schemas/GceCloudImage.dhall sha256:511c9cc09c07641ab2a5f6bdd21823956dea1c919e7f4a0e75a29bcf221e95a9
, GcePool =
    ./schemas/GcePool.dhall sha256:bb205553c0e7683a3c7213ddd94fbaf3206ab9591f0f09bc1c30b90a1fd3728f
, GcePoolLabel =
    ./schemas/GcePoolLabel.dhall sha256:2c95619c0577ea2f3c3853ba1d8571f32d2c512e5e200d258dc57192e556b1d4
, Kubernetes =
    ./schemas/Kubernetes.dhall sha256:d323d858d10846b918d16fec47fac1013d0cfb47d6826bd5a6a0bda362bbd657
, KubernetesPool =
    ./schemas/KubernetesPool.dhall sha256:93812f04448ee35cf687f2bfe7db869dd2129831e08657fbfbc5a76daec49220
, KubernetesPoolLabel =
    ./schemas/KubernetesPoolLabel.dhall sha256:4295ac81372228940148a4706924afb9015eae72c44739d4a4b662674ea36bba
, Label =
    ./schemas/Label.dhall sha256:57c0b99faadd31679c690a00b2eac11f17245e291e8f0002fe17bd07f85cbbb7
, Openshift =
    ./schemas/Openshift.dhall sha256:be8357fd3626fadd7f09672c4fb65c02d5622a19d9764ddda0a67fd66956669a
, OpenshiftPool =
    ./schemas/OpenshiftPool.dhall sha256:5b3f21686d6dbeec95a9ff11e060984f0a15e03c31c391e17703b660cf45f486
, OpenshiftPoolLabel =
    ./schemas/OpenshiftPoolLabel.dhall sha256:51da6af995ba538a91fa165fc6e3b1b4325604cd26c48db95d1d11d66b0ce53a
, Openshiftpods =
    ./schemas/Openshiftpods.dhall sha256:493681520c8d6e76d0fea162a2838497d47396cc6d1028fae91c7b2771cf51b6
, OpenshiftpodsPool =
    ./schemas/OpenshiftpodsPool.dhall sha256:5b438c475c4533703197a7a07c03ea8dabca67ac3dbbba3d69a1fb4f6e6b208b
, OpenshiftpodsPoolLabel =
    ./schemas/OpenshiftpodsPoolLabel.dhall sha256:d3eebc9b500d7fa2674db854ed5c9ba8c365311023bddffa013853eb8b640c83
, Openstack =
    ./schemas/Openstack.dhall sha256:897d7acb9b8ad52c8d7a700901f40735f46084cb19b27671ff51cf4f1bcd324c
, OpenstackCloudImage =
    ./schemas/OpenstackCloudImage.dhall sha256:100b970c9a5d54f76292918e49472ad40924c52f8ff89081c2850adbfc0ff193
, OpenstackDiskimage =
    ./schemas/OpenstackDiskimage.dhall sha256:bf0e1754cf27f0600ec31ab8b0827e0991c4248aaea74391fdfe9bbca38dafe8
, OpenstackPool =
    ./schemas/OpenstackPool.dhall sha256:230abee847925bc354a5b03afd06a8be50eddcc8b1c51e218c027f5af09b8bdc
, OpenstackPoolLabel =
    ./schemas/OpenstackPoolLabel.dhall sha256:4305b96b1f0af8f1058b113d5b1dcf7a2f0bcdd1b478bb71df15034bb4c5032b
, Providers =
    ./schemas/Providers.dhall sha256:8d6b7b5d3587d04244e9c136e422b11cb0ab12c451a1c2d9cf56592b86a5706b
, Static =
    ./schemas/Static.dhall sha256:bfa93ce2ae347b5fbade2965a49e2fc2d658589a2137c1cff08451b3a36a5a3b
, StaticPool =
    ./schemas/StaticPool.dhall sha256:b7c69024d14be5c261e6b7ab6197578082ca23aad0f048c2a6bb65e283cf1b02
, StaticPoolNode =
    ./schemas/StaticPoolNode.dhall sha256:bdfa7227f6c8ed280b9fe4ad9fd0f219728e3da367e3d7bf04887cc73ce93f10
, WebApp =
    ./schemas/WebApp.dhall sha256:0e3cde952af63619172b62506a55c64b2f4ce4dce4c900b9603d79848c151f4a
, ZookeeperServer =
    ./schemas/ZookeeperServer.dhall sha256:8fb4a851f4a2d610e81ba77566531aef518f4452317c436bdec61a0e32d95135
}
