diskimages:
  - elements:
      - centos-minimal
      - nodepool-minimal
      - zuul-worker-user
      - enforce-sshd-config
      - rpm-factory
      - ansible
      - common-packages
      - sf-ci-packages
      - scl
    formats:
      - raw
    name: dib-centos-7
    username: zuul-worker
  - dib-cmd: "/usr/bin/dib-virt-customize /etc/nodepool/virt_images/cloud-centos-8.yaml"
    name: cloud-centos-8
    python-path: /usr/bin/python3
labels:
  - min-ready: 1
    name: dib-centos-7
  - min-ready: 1
    name: cloud-centos-8
zookeeper-servers:
  - chroot: /nodepool
    host: localhost
    port: 2181
